version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: habrpguser
      DB_PASSWORD: pgpwd4habr
      DDL_AUTO: create-drop
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - "5432:5432"