name: build and deploy for dev
on:
  pull_request:
    branches:
      - 'dev'
    types: [closed]



jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/signalserverdevops:dev.backend
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 10m
          stack_file_name: docker-compose.yaml
          script: | 
            docker login -u ${{  secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            cd ${{ secrets.REPO_NAME }}
            export BOT_TOKEN_DEV=${{ secrets.BOT_TOKEN_DEV }}
            export BOT_TAG_DEV=dev
            docker-compose -f docker-compose-dev.yml down
            docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/signalserverdevops:dev.backend
            docker-compose -f docker-compose-dev.yml up -d
