spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:habrpguser}
    password: ${DB_PASSWORD:pgpwd4habr}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mvc:
    validation:
      enabled: true

  mail:
    host: smtp.mail.ru
    port: 465
    username: signal.test.mail@mail.ru
    password: AxXgiv70tKf4DTGsumgW
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true


server:
  port: 8080

bot:
  token: 6272045013:AAGyZKGFDX_5E5jQALnj1FudvH2-yFxtQEs
  username: dafghrhsfjhfjytBOT